export const RESET_GAME = 'RESET_GAME';

export const TOGGLE_ALL_CARDS = 'TOGGLE_ALL_CARDS';
export const OPEN_CARD = 'OPEN_CARD';
export const DISABLE_CARD = 'DISABLE_CARD';
export const DISACTIVE_ALL_CARDS = 'DISACTIVE_ALL_CARDS';

export const SET_GAME_ACTION = 'SET_GAME_ACTION';
export const SET_COUNTER = 'SET_COUNTER';
export const SET_GAME_RESULT = 'SET_GAME_RESULT';

export const SET_GAME_SETTINGS = 'SET_GAME_SETTINGS';
export const SET_CARDS = 'SET_CARDS';
